Add Kafka docs
AVSystem/developer-zone pull request #141
Opened 2023-08-08 17:41 UTC by laurensslats

2023-08-09 11:39 UTC, mikegpl requested changes

2023-08-09 11:39 UTC, mikegpl commented on docs/Cloud_integrations/images/kafka-configuration.png
I think we should at least blur here the parts of `bootstrap.servers` and `sasl.jaas.config` where the credentials are visible

2023-08-09 11:39 UTC, mikegpl commented on docs/Cloud_integrations/images/kafka-config-set.png
Mind that `domainId` is here set to. `/lwm2m_workshops/grabowski` and in other places it is `/embedded`

2023-08-09 11:39 UTC, mikegpl commented on docs/Cloud_integrations/images/kafka-event-arrived.png
The same goes for domain here

2023-08-09 11:39 UTC, mikegpl commented on docs/Cloud_integrations/kafka.md
> +Connect {{ coiote_long_name }} to your Kafka cluster by creating a Kafka event handler.
I think it's worth pointing out that you can connect with `Azure Event Hub`, e.g. by writing `to your Kafka cluster or Azure Event Hub` - I think more people are used to working with Azure services than to working with Kafka clusters (either managed by themselves or by other companies)

2023-08-09 11:39 UTC, mikegpl commented on docs/Cloud_integrations/kafka.md
> +Specify the **Topic** and **Producer configuration** to set up the conntion with a Kafka cluster.
Typo: `conntion` => `connection`

2023-08-10 08:41 UTC, laurensslats commented on docs/Cloud_integrations/images/kafka-config-set.png
Good observation, this doesn't hurt IMHO

2023-08-10 09:00 UTC, mikegpl approved these changes
LGTM :)

2023-08-10 09:05 UTC, merged