New fixes in Nordic, M5Stick and STM B-L475E
AVSystem/developer-zone pull request #66
Opened 2022-09-29 12:16 UTC by malw4

2022-09-29 12:37 UTC, Mierunski requested changes

2022-09-29 12:37 UTC, Mierunski commented on docs/Anjay_integrations/Anjay_Nordic_integration/Thingy91.md
> +            This is your own password which you will need further.
```suggestion
            This is your own password which you will need in the next steps.
```

2022-10-04 10:24 UTC, JZimnol reviewed
Some language nits, some important suggestions changed + the ones we talked about in the office face-to-face.

2022-10-04 10:24 UTC, JZimnol commented on docs/Anjay_integrations/Anjay_Nordic_integration/nRF9160.md
>                - In the **Key identity** field, type `test_device`
```suggestion
              - In the **Key identity** field, type the same name as in the `Endpoint name` field
```

2022-10-04 10:24 UTC, JZimnol commented on docs/Anjay_integrations/Anjay_Nordic_integration/nRF9160.md
>                - In the **Key identity** field, type `test_device`
Or remove this section completely, because the Key identity field is filled automatically.

2022-10-04 10:24 UTC, JZimnol commented on docs/Anjay_integrations/ESP32_integration/M5Stick.md
>  0. Install the `esptool.py`:
You need to put this step before the `tip` section ("Before flashing the device you should erase the flash...")

2022-10-04 10:24 UTC, JZimnol commented on docs/Anjay_integrations/Anjay_Nordic_integration/nRF9160.md
>      ![Registered device](images/registered_device.png "Registered device")
It's worth mentioning to "Use the `anjay start` command to run the Client"

2022-10-04 10:24 UTC, JZimnol commented on docs/Anjay_integrations/Anjay_ST_integration/B-L475E-IOT01A.md
>      ![Registered device](images/registered_device.png "Registered device")
It's worth mentioning to "Use the `anjay start` command to run the Client"

2022-10-06 14:22 UTC, merged