Added pico w tutorial
AVSystem/developer-zone pull request #77
Opened 2022-11-28 14:25 UTC by malw4

My changes are in the RaspberryPi-Pico-W file.
Implementing_LwM2M_objects_on_RaspberryPi file was only dragged to this folder.

2022-11-29 10:40 UTC, malw4 commented
@JZimnol review please

2022-12-04 16:17 UTC, JZimnol reviewed
@malw4 reviewed. There are some nits and some important suggestions. 
I know that you've only moved the `Implementing LwM2M objects...` file, but I have some suggestions there too. Please look at them.

2022-12-04 16:17 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/Implementing_LwM2M_objects_on_RaspberryPi.md
> +      $ sudo svetovid-fsdmtool generate --object 3345 --output-dir /etc/svetovid/dm --generator python`
```suggestion
      $ sudo svetovid-fsdmtool generate --object 3345 --output-dir /etc/svetovid/dm --generator python
```

2022-12-04 16:17 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/Implementing_LwM2M_objects_on_RaspberryPi.md
> +0. Type in the terminal: `cd /etc/svetovid/dm/3345/resources ./5550 read`.
```suggestion
0. Type in the terminal: `cd /etc/svetovid/dm/3345/resources && ./5550 read`.
```

2022-12-04 16:17 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/Implementing_LwM2M_objects_on_RaspberryPi.md
> +       ![Joystick button object](images/button.png "3345")
Missing image here.

2022-12-04 16:17 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/RaspberryPi-Pico-W.md
> +0. Clone Raspberry Pi Pico SDK and FreeRTOS kernel into a base directory, parallel to Anjay-pico-client Github repository:
I would **bold** the `Raspberry Pi Pico SDK` and `FreeRTOS kernel` names.

2022-12-04 16:17 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/RaspberryPi-Pico-W.md
> +0. Build the project with `<ssid>` and `<pass>` replaced with your WIFI name and password respectively. LwM2M Client Endpoint Name is also configured by `<endpoint_name>` parameter:
What about `<identity>` and `<psk>`?

2022-12-04 16:17 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/RaspberryPi-Pico-W.md
> +0. After Pico will be programmed, reset and start running the code.
```suggestion
0. One Pico is programmed, the board will restart and start running the code.
```
Or something like that.

2022-12-04 16:17 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/RaspberryPi-Pico-W.md
> +         - In the **Security mode** section, select the security mode you choose in [Compile the application](#compile-the-application) step:
```suggestion
         - In the **Security mode** section, select the security mode you've choosen in [Compile the application](#compile-the-application) step.
```

2022-12-04 16:17 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/RaspberryPi-Pico-W.md
> +            - In the **Key** field, the shared secret used in the device-server authentication.
Can you move this `Note` more to the right so it's fully below the `In the Security mode section` bullet point?

2022-12-04 16:17 UTC, JZimnol commented on mkdocs.yml
> +            - 'Raspberry Pi Pico boards':
```suggestion
            - 'Raspberry Pi boards':
```

2022-12-05 10:23 UTC, malw4 commented on docs/Anjay_integrations/RaspberryPi_integration/Implementing_LwM2M_objects_on_RaspberryPi.md
> +It features the FSDM (File System Data Model) in which LwM2M objects are mapped to folders that follow a particular schema, and executables behave as expected by the LwM2M client that loads and manag
@mkrawczyk-avs what do you think?

2022-12-07 12:15 UTC, JZimnol reviewed
@malw4 second round of review completed.

2022-12-07 12:15 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/Implementing_LwM2M_objects_on_RaspberryPi.md
> +         - In the **Device ID** enter your board endpoint name, e.g. `test_device`.
`e.g. test_device` but you have `raspberry_pi_test` on the screenshot.

2022-12-07 12:15 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/Implementing_LwM2M_objects_on_RaspberryPi.md
> +    Your RaspberryPi-based device will feature a number of default LwM2M objects provided by Svetovid, for instance the temperature object `/3303`.
There is no `/3303` object on the screenshot (it is added later in the article). Maybe change it to the `3311 Light Control`?

2022-12-07 12:15 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/Implementing_LwM2M_objects_on_RaspberryPi.md
> +        You can analyze the resource implementation in the `/etc/svetovid/dm/3303 folder`. For more details, see the [Svetovid page on GitHub](https://github.com/AVSystem/Svetovid-raspberry-client).
```suggestion
        You can analyze the resource implementation in the `/etc/svetovid/dm/3303` folder. For more details, see the [Svetovid page on GitHub](https://github.com/AVSystem/Svetovid-raspberry-client).
```

2022-12-11 16:24 UTC, laurensslats requested changes

2022-12-19 07:54 UTC, JZimnol reviewed
@malw4 Added one last comment.

2022-12-19 07:54 UTC, JZimnol commented on docs/Anjay_integrations/RaspberryPi_integration/Implementing_LwM2M_objects_on_RaspberryPi.md
> +2. Check if the GrovePi libraries are working correctly:
```suggestion
        bash ./update_grovepi.sh
    ```

2. Check if the GrovePi libraries are working correctly:
```

The "1." and "2." are still not in line :/

2023-01-09 08:53 UTC, JZimnol commented
@malw4 approved.

2023-01-13 07:40 UTC, merged